# This is a basic workflow to help you get started with Actions
name: Bump version

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for main and solution branches
  push:
    branches: [ main, solution ]
  pull_request:
    branches: [ main, solution ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Bump version
        uses: remorses/bump-version@js
        with:
            version_file: ./VERSION
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update logo
        run: |
          python -m actions_workshop --version VERSION --base-logo logo_base.png --new-logo logo.png 
      
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
          

